# Dependabot configuration for automated dependency updates
version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ypratap11"
    assignees:
      - "ypratap11"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "streamlit"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ypratap11"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ypratap11"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Helm dependencies (if using Helm charts)
  - package-ecosystem: "gitsubmodule"
    directory: "/helm"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "ypratap11"
    commit-message:
      prefix: "helm"
      include: "scope"
    labels:
      - "dependencies"
      - "helm"